### ISSUE TITLE
Issue installing packages using bmo add command

### ISSUE THREAD

**Issue by BReul** [libertymutual/bmo#27]
Running `bmo add mongodb as mongo` yields the following stack trace

`BMO CLI v 0.7.1
(node:10446) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at Command.<anonymous> (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/dependencies/commands/add/command.js:11:11)
    at Command.listener [as _actionHandler] (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:1460:12)
    at Command.parse (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/commander/index.js:1318:10)
    at Object.run (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/dependencies/run/index.js:8:20)
    at Bundle.run (/Users/benjaminreul/.nvm/versions/node/v12.16.1/lib/node_modules/@b-mo/cli/node_modules/@b-mo/bundle/index.js:100:39)
    at runMicrotasks (<anonymous>)
(node:10446) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10446) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by TSteele27** [comment]
fixed by #31
